//! Template processing for code generation.
//!
//! This module provides template-based code generation functionality
//! for processing analysis results into game resources.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use anyhow::Result;

use dl_types::analysis::base::Inventory;
use dl_types::analysis::raw::EntityCategory;

/// Template manager for code generation
#[derive(Debug, Clone)]
pub struct TemplateManager {
    /// Available templates by category
    templates: HashMap<String, String>,
}

impl TemplateManager {
    pub fn new() -> Result<Self> {
        let mut templates = HashMap::new();
        
        // Add basic templates
        templates.insert("regions".to_string(), "regions_analysis.j2".to_string());
        templates.insert("settlements".to_string(), "settlements_analysis.j2".to_string());
        templates.insert("factions".to_string(), "factions_analysis.j2".to_string());
        templates.insert("dungeons".to_string(), "dungeons_analysis.j2".to_string());
        
        Ok(Self { templates })
    }

    pub fn render_entity_template(
        &self,
        category: &EntityCategory,
        inventory: &Inventory,
        metadata: Option<&HashMap<String, String>>,
    ) -> Result<String> {
        // For now, just use basic template rendering
        let mut lines = vec![
            format!("//! Generated models for {} entities", category.as_str()),
            "//! This file was generated by the analysis system. Do not edit manually.".to_string(),
            "".to_string(),
            "use serde::{Deserialize, Serialize};".to_string(),
            "use std::collections::HashMap;".to_string(),
            "".to_string(),
        ];

        // Generate structs for each entity
        for entity in &inventory.entities {
            lines.push(format!("/// {}", entity.description.as_ref().unwrap_or(&"Generated entity".to_string())));
            lines.push("#[derive(Debug, Clone, Serialize, Deserialize)]".to_string());
            lines.push(format!("pub struct {} {{", entity.name));

            for field in &entity.fields {
                if let Some(desc) = &field.description {
                    lines.push(format!("    /// {}", desc));
                }
                lines.push(format!("    pub {}: {},", field.name, field.field_type));
            }

            lines.push("}".to_string());
            lines.push("".to_string());
        }

        Ok(lines.join("\n"))
    }
}
