//! Build script for game-engine to generate assets and database integration

use std::env;
use std::fs;
use std::path::Path;

/// Check if we have pre-generated assets from a previous run
fn check_for_generated_assets(generated_dir: &Path) -> bool {
    // Check for essential directories that should contain AI-generated content
    let required_dirs = ["ui", "dialogue", "maps", "levels", "audio", "decay", "mounts"];
    let mut found_count = 0;
    
    for dir in &required_dirs {
        let dir_path = generated_dir.join(dir);
        if dir_path.exists() && dir_path.is_dir() {
            // Check if directory has actual content
            if let Ok(entries) = fs::read_dir(&dir_path) {
                if entries.count() > 0 {
                    found_count += 1;
                    println!("cargo:warning=Found {} assets", dir);
                }
            }
        }
    }
    
    // Require at least half of the directories to have content
    found_count >= required_dirs.len() / 2
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let out_dir = env::var("OUT_DIR")?;
    let out_path = Path::new(&out_dir);
    
    println!("cargo:rerun-if-changed=../build-tools");
    println!("cargo:rerun-if-changed=../game-database");
    println!("cargo:rerun-if-env-changed=OPENAI_API_KEY");
    
    // Create generated code directory
    let generated_dir = out_path.join("generated");
    fs::create_dir_all(&generated_dir)?;
    
    // We don't generate runtime code anymore - that's just normal code in game-engine!
    // Only generate the actual CONTENT/ASSETS
    
    // Check if we have pre-generated assets
    let assets_exist = check_for_generated_assets(&generated_dir);
    
    if !assets_exist {
        // During development, create minimal placeholder assets to allow compilation
        println!("cargo:warning=No AI-generated assets found - creating development placeholders");
        
        // Create minimal directories for development
        let required_dirs = ["ui", "dialogue", "maps", "levels", "audio", "decay", "mounts"];
        for dir in &required_dirs {
            let dir_path = generated_dir.join(dir);
            fs::create_dir_all(&dir_path)?;
            
            // Create a minimal placeholder file
            let placeholder_file = dir_path.join("development_placeholder.json");
            fs::write(&placeholder_file, r#"{"development_mode": true, "content": "placeholder"}"#)?;
        }
        
        println!("cargo:warning=Development mode: Created placeholder assets for compilation");
        println!("cargo:warning=For full functionality, run AI asset generation pipeline");
    }
    
    println!("cargo:warning=Found AI-generated assets, proceeding with build");
    
    Ok(())
}

// Build script no longer generates ANY assets or code
// Assets must be pre-generated by the overnight agent
// Runtime code is in game-engine/src/ modules
